//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: xlsc_battle_gold_gold.proto
namespace xlsc.battle_gold
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GOLD")]
  public partial class GOLD : global::ProtoBuf.IExtensible
  {
    public GOLD() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _commnet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"commnet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string commnet
    {
      get { return _commnet; }
      set { _commnet = value; }
    }
    private string _init;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"init", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string init
    {
      get { return _init; }
      set { _init = value; }
    }
    private string _nature_growth;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nature_growth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nature_growth
    {
      get { return _nature_growth; }
      set { _nature_growth = value; }
    }
    private string _monster_common;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"monster_common", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string monster_common
    {
      get { return _monster_common; }
      set { _monster_common = value; }
    }
    private string _monster_elite;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"monster_elite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string monster_elite
    {
      get { return _monster_elite; }
      set { _monster_elite = value; }
    }
    private string _monster_super;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"monster_super", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string monster_super
    {
      get { return _monster_super; }
      set { _monster_super = value; }
    }
    private string _hero_kill;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"hero_kill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hero_kill
    {
      get { return _hero_kill; }
      set { _hero_kill = value; }
    }
    private string _hero_assist;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"hero_assist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hero_assist
    {
      get { return _hero_assist; }
      set { _hero_assist = value; }
    }
    private string _tower_destroy;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"tower_destroy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tower_destroy
    {
      get { return _tower_destroy; }
      set { _tower_destroy = value; }
    }
    private string _tower_share;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"tower_share", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tower_share
    {
      get { return _tower_share; }
      set { _tower_share = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GOLD_ARRAY")]
  public partial class GOLD_ARRAY : global::ProtoBuf.IExtensible
  {
    public GOLD_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<xlsc.battle_gold.GOLD> _items = new global::System.Collections.Generic.List<xlsc.battle_gold.GOLD>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<xlsc.battle_gold.GOLD> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}