//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: xlsc_goods_goods_conf.proto
namespace xlsc.goods
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GOODS_CONF")]
  public partial class GOODS_CONF : global::ProtoBuf.IExtensible
  {
    public GOODS_CONF() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _short_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"short_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string short_name
    {
      get { return _short_name; }
      set { _short_name = value; }
    }
    private readonly global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF.InternalType_Test> _Test = new global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF.InternalType_Test>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Test", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF.InternalType_Test> Test
    {
      get { return _Test; }
    }
  
    private uint _resource = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _up_shelves_time = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"up_shelves_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint up_shelves_time
    {
      get { return _up_shelves_time; }
      set { _up_shelves_time = value; }
    }
    private uint _off_shelves_time = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"off_shelves_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint off_shelves_time
    {
      get { return _off_shelves_time; }
      set { _off_shelves_time = value; }
    }
    private int _sex_detail = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex_detail", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex_detail
    {
      get { return _sex_detail; }
      set { _sex_detail = value; }
    }
    private int _is_time_limit = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"is_time_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int is_time_limit
    {
      get { return _is_time_limit; }
      set { _is_time_limit = value; }
    }
    private uint _smallIconType = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"smallIconType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint smallIconType
    {
      get { return _smallIconType; }
      set { _smallIconType = value; }
    }
    private string _smallIconName = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"smallIconName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string smallIconName
    {
      get { return _smallIconName; }
      set { _smallIconName = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_Test")]
  public partial class InternalType_Test : global::ProtoBuf.IExtensible
  {
    public InternalType_Test() {}
    
    private uint _is_plural = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_plural", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint is_plural
    {
      get { return _is_plural; }
      set { _is_plural = value; }
    }
    private readonly global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF.InternalType_Test.InternalType_Testdd> _Testdd = new global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF.InternalType_Test.InternalType_Testdd>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Testdd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF.InternalType_Test.InternalType_Testdd> Testdd
    {
      get { return _Testdd; }
    }
  
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private uint _color = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _desc_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"desc_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> desc_list
    {
      get { return _desc_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_Testdd")]
  public partial class InternalType_Testdd : global::ProtoBuf.IExtensible
  {
    public InternalType_Testdd() {}
    
    private uint _max_plural_num = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"max_plural_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint max_plural_num
    {
      get { return _max_plural_num; }
      set { _max_plural_num = value; }
    }
    private uint _rarity = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rarity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rarity
    {
      get { return _rarity; }
      set { _rarity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GOODS_CONF_ARRAY")]
  public partial class GOODS_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public GOODS_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF> _items = new global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<xlsc.goods.GOODS_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}